[package]
name = "wayland-obs-shortcuts"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
obws = "0.14.0"
tokio = { version = "1.45.1", features = ["macros"] }

[profile.release]
lto = true
strip = true
